name: Verificação Automática de Sorteio
on:
  schedule:
    # Executa a cada 5 minutos entre 20:45 e 21:15 (horário UTC-3 / Brasil)
    - cron: '*/5 23 * * *'  # 20:00-20:59 Brasil = 23:00-23:59 UTC
    - cron: '*/5 0 * * *'   # 21:00-21:59 Brasil = 00:00-00:59 UTC

jobs:
  verificar-sorteio:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar função de verificação no Supabase
        run: |
          curl -X POST ${{ secrets.SUPABASE_URL }}/rest/v1/rpc/executar_verificacao_sorteio \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=minimal"
      
      - name: Registrar execução
        if: always()
        run: |
          echo "Verificação de sorteio executada em $(date)" 